_target_: src.models.rsna_module_manual.RSNALitModule

optimizer:
  _target_: src.optimizer.sam.SAM
  _partial_: true
  rho: 0.5
  lr: 0.1
  weight_decay: 0.0005
  momentum: 0.9

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.05
  patience: 2

net:
  _target_: src.models.components.resnet18.ResNet18
  num_classes: 1
